<?php /*
 
BEISPIEL AREA
 
ausschlaggebend ist dieses IF hier:
if(!Website_Tool_Area::ajaxInclude($this)) {
 
damit lässt sich bestimmen was per ajaxInclude angezeigt wird und was immer ausgegeben bzw. ausgeführt werden soll, wie z.B. Metadaten usw.
nur der Parameter $this ist verpflichtend, alles andere ist optional (position & html attribute) - standard position ist "after"
 
*/ ?>
 
<?php
    // add autogenerated meta description
    $this->headMeta()->setName('description', Website_Tool_Text::cutStringRespectingWhitespace(Website_Tool_Text::getStringAsOneLine(strip_tags($this->wysiwyg("content")->getData())), 160));
?>
 
<?php if(!Website_Tool_Area::ajaxInclude($this, "after", ["class" => "my-custom-class loading-indicator ...", 'data-storage' => Website_Tool_Text::getStorageKey($this)])) { ?>
    <section class="area-wysiwyg">
 
        <?php $this->glossary()->start(); ?>
            <?= $this->wysiwyg("content"); ?>
        <?php $this->glossary()->stop(); ?>
 
    </section>
<?php } ?>